// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOg2EcS-q0MEMjcAtP_KXyOFZChQT-b0',
    appId: '1:438868741822:web:63e83125cd18dac62758ef',
    messagingSenderId: '438868741822',
    projectId: 'al-quran-f9fc5',
    authDomain: 'al-quran-f9fc5.firebaseapp.com',
    storageBucket: 'al-quran-f9fc5.firebasestorage.app',
    measurementId: 'G-WPF89Y1WGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Z046U5aSMesd6NlobuUUS6nqMkyeroc',
    appId: '1:438868741822:android:129b0cf63ec223c72758ef',
    messagingSenderId: '438868741822',
    projectId: 'al-quran-f9fc5',
    storageBucket: 'al-quran-f9fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKdgqTcn07N9PM1zCTK0kVUqUGMI1PWOU',
    appId: '1:438868741822:ios:58d4ec5f6c47195b2758ef',
    messagingSenderId: '438868741822',
    projectId: 'al-quran-f9fc5',
    storageBucket: 'al-quran-f9fc5.firebasestorage.app',
    iosBundleId: 'com.example.alQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKdgqTcn07N9PM1zCTK0kVUqUGMI1PWOU',
    appId: '1:438868741822:ios:58d4ec5f6c47195b2758ef',
    messagingSenderId: '438868741822',
    projectId: 'al-quran-f9fc5',
    storageBucket: 'al-quran-f9fc5.firebasestorage.app',
    iosBundleId: 'com.example.alQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyOg2EcS-q0MEMjcAtP_KXyOFZChQT-b0',
    appId: '1:438868741822:web:67c4c5cf8a76863c2758ef',
    messagingSenderId: '438868741822',
    projectId: 'al-quran-f9fc5',
    authDomain: 'al-quran-f9fc5.firebaseapp.com',
    storageBucket: 'al-quran-f9fc5.firebasestorage.app',
    measurementId: 'G-Z0ENS9WFEH',
  );
}
